import { ThemeProvider } from "./context/ThemeContext";
import "./globals.css"; // Ensure globals.css has the correct Tailwind imports

export const metadata = {
  title: "DeepSoul",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider> {children}</ThemeProvider>
      </body>
    </html>
  );
}
