import { ThemeProvider } from "./context/ThemeContext";
import "./globals.css"; // Ensure globals.css has the correct Tailwind imports
import {Pacifico} from "next/font/google";
export const metadata = {
  title: "DeepSoul",
  description: "Generated by create next app",
};

const pacifico = Pacifico({
  subsets: ["latin"],
  weight: "400",
  variable: "--font-pacifico",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${pacifico.variable} antialiased`} >
        <ThemeProvider> {children}</ThemeProvider>
      </body>
    </html>
  );
}
